services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  client_handler:
    container_name: client_handler
    environment:
      - NEXT_STAGE_INSTANCES=2
    build:
      context: .
      dockerfile: ./client_handler/Dockerfile
    entrypoint: /client_handler
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    entrypoint: /client
    restart: on-failure
    depends_on:
      - client_handler
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml

  duration_merger:
    container_name: duration_merger
    environment:
      - PREV_STAGE_INSTANCES=2
      - NEXT_STAGE_INSTANCES=1
    build:
      context: .
      dockerfile: ./duration_merger/Dockerfile
    entrypoint: /duration_merger
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy


  duration_averager_0:
    container_name: duration_averager_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=2
      - NEXT_STAGE_INSTANCES=1
    build:
      context: .
      dockerfile: ./duration_averager/Dockerfile
    entrypoint: /duration_averager
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  duration_averager_1:
    container_name: duration_averager_1
    environment:
      - ID=1
      - PREV_STAGE_INSTANCES=2
      - NEXT_STAGE_INSTANCES=1
    build:
      context: .
      dockerfile: ./duration_averager/Dockerfile
    entrypoint: /duration_averager
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
        

  precipitation_filter_0:
    container_name: precipitation_filter_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=3
      - NEXT_STAGE_INSTANCES=2
    build:
      context: .
      dockerfile: ./precipitation_filter/Dockerfile
    entrypoint: /precipitation_filter
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  precipitation_filter_1:
    container_name: precipitation_filter_1
    environment:
      - ID=1
      - PREV_STAGE_INSTANCES=3
      - NEXT_STAGE_INSTANCES=2
    build:
      context: .
      dockerfile: ./precipitation_filter/Dockerfile
    entrypoint: /precipitation_filter
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
   

  weather_joiner_0:
    container_name: weather_joiner_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=2
      - NEXT_STAGE_INSTANCES=2
    build:
      context: .
      dockerfile: ./weather_joiner/Dockerfile
    entrypoint: /weather_joiner
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  weather_joiner_1:
    container_name: weather_joiner_1
    environment:
      - ID=1
      - PREV_STAGE_INSTANCES=2
      - NEXT_STAGE_INSTANCES=2
    build:
      context: .
      dockerfile: ./weather_joiner/Dockerfile
    entrypoint: /weather_joiner
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  weather_joiner_2:
    container_name: weather_joiner_2
    environment:
      - ID=2
      - PREV_STAGE_INSTANCES=2
      - NEXT_STAGE_INSTANCES=2
    build:
      context: .
      dockerfile: ./weather_joiner/Dockerfile
    entrypoint: /weather_joiner
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
   

  data_dropper_0:
    container_name: data_dropper_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=1
      - WEATHER_JOINER_INSTANCES=3
      - STATIONS_JOINER_INSTANCES=1
    build:
      context: .
      dockerfile: ./data_dropper/Dockerfile
    entrypoint: /data_dropper
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  data_dropper_1:
    container_name: data_dropper_1
    environment:
      - ID=1
      - PREV_STAGE_INSTANCES=1
      - WEATHER_JOINER_INSTANCES=3
      - STATIONS_JOINER_INSTANCES=1
    build:
      context: .
      dockerfile: ./data_dropper/Dockerfile
    entrypoint: /data_dropper
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
   
